- name: create service user
  user:
    name: "{{ kafka_run_user }}"
    password: "{{ kafka_run_pass | password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: ensure install dir is exists
  file:
    path: "{{ kafka_install_dir }}"
    state: directory
    owner: "{{ kafka_run_user }}"
    group: "{{ kafka_run_group }}"

- name: check kafka is installed or not
  stat:
    path: "{{ kafka_install_dir }}/bin/kafka-server-start.sh"
  register: kafka_status

- name: download kafka
  unarchive:
    src: "{{ kafka_download_url }}"
    dest: "{{ kafka_install_dir }}"
    remote_src: yes
    extra_opts: "--strip-components=1"
    owner: "{{ kafka_run_user }}"
    group: "{{ kafka_run_group }}"
  when: not kafka_status.stat.exists

- name: create data directory
  file:
    path: "{{ kafka_log_dir }}"
    owner: "{{ kafka_run_user }}"
    group: "{{ kafka_run_group }}"
    recurse: true
    state: directory
